### ISSUE TITLE
get_streams.xml API request for kanal9play returns http error 500

### ISSUE THREAD

**Issue by kabniel** [jackuess/pirateplay.se#1]
First of all thanks for a great service!
I'm currently hacking on some code to stream web-tv to my PS3 and i'm using the pirateplay API to get the stream urls.

While adding kanal9play i noticed that get_streams.xml returns a http error 500,  for example:
http://pirateplay.se/api/get_streams.xml?url=http://kanal9play.se/program/play/saturdaynightlive-s38e02

I downloaded the lib/pirateplay code and ran it on my machine in debug mode, and i think the problem is at https://github.com/jackuess/pirateplay.se/blob/master/lib/pirateplay/services.py#L176
There's a double slash after the brightcove.com domain which results in a 503 error, after replacing the double-slash with a single-slash it seems to be working fine.

**Comment by jackuess** [comment]
You're quite right, fixed!
