### ISSUE TITLE
RFE: Running as CLI app.

### ISSUE THREAD

**Issue by leamas** [jackuess/pirateplay.se#2]
If you have a scenario like mythtv, there is a need to run pirateplay from the command line, without any GUI, giving some options like url, local filename, quality... 

I might be interested in doing this, but have you some general advice on how to do it?

**Comment by jackuess** [comment]
lib/pirateplay/main.py is perfectly runnable from the command line. Try python 'lib/pirateplay/main.py --help'. An other option is [the webb API](http://pirateplay.se/api/manual.html).
